// Allow / restrict lists for V1.  These also seed the corresponding tables.

export const ALLOWED_CATEGORIES: { name: string; notes?: string }[] = [
  { name: 'Home & Kitchen' },
  { name: 'Storage & Organization' },
  { name: 'Patio, Lawn & Garden' },
  { name: 'Tools & Home Improvement' },
  { name: 'Office Products' },
  { name: 'Pet Supplies', notes: 'Exclude ingestibles, medical, supplements, flea/tick products' },
  { name: 'Arts, Crafts & Sewing' },
  { name: 'Sporting Goods', notes: 'Exclude weapons / safety gear' },
  { name: 'Party Supplies', notes: 'Exclude copyrighted characters' },
  { name: 'Home Décor' },
  { name: 'Cleaning Tools', notes: 'Exclude chemicals' },
  { name: 'Garage Organization' },
  { name: 'Kitchen Organization' },
  { name: 'Craft Storage' },
];

export const RESTRICTED_CATEGORIES: { name: string; reason: string; hardBlock: boolean }[] = [
  { name: 'Health & Beauty', reason: 'Compliance / IP risk', hardBlock: true },
  { name: 'Medical Devices', reason: 'FDA / eBay restricted', hardBlock: true },
  { name: 'Supplements', reason: 'FDA / eBay restricted', hardBlock: true },
  { name: 'Food / Grocery', reason: 'Perishable / FDA', hardBlock: true },
  { name: 'Cosmetics', reason: 'FDA / IP risk', hardBlock: true },
  { name: 'Baby Safety Products', reason: 'Safety / liability', hardBlock: true },
  { name: 'Car Seats', reason: 'Safety / liability', hardBlock: true },
  { name: 'Weapons', reason: 'eBay restricted', hardBlock: true },
  { name: 'Firearms', reason: 'eBay restricted', hardBlock: true },
  { name: 'Self-Defense Products', reason: 'eBay restricted', hardBlock: true },
  { name: 'Hazardous Materials', reason: 'Shipping restricted', hardBlock: true },
  { name: 'Pesticides', reason: 'EPA / shipping restricted', hardBlock: true },
  { name: 'Chemicals', reason: 'Shipping restricted', hardBlock: true },
  { name: 'Luxury Brands', reason: 'VeRO / counterfeit risk', hardBlock: true },
  { name: 'Fashion (counterfeit-prone)', reason: 'VeRO / IP risk', hardBlock: true },
  { name: 'Branded Electronics Accessories', reason: 'IP / authenticity risk', hardBlock: true },
  { name: 'Software / Digital Goods', reason: 'Licensing / eBay rules', hardBlock: true },
  { name: 'Trading Cards / Collectibles', reason: 'Authentication risk', hardBlock: true },
  { name: 'Fitment-Heavy Automotive Parts', reason: 'Returns / compatibility', hardBlock: true },
];

export const BLACKLIST_BRANDS: string[] = [
  // VeRO / luxury / IP-protected examples - extend in DB.
  'Apple',
  'Nike',
  'Adidas',
  'Disney',
  'Marvel',
  'Lego',
  'Louis Vuitton',
  'Gucci',
  'Chanel',
  'Rolex',
  'Sony',
  'Samsung',
  'Microsoft',
  'Nintendo',
  'PlayStation',
  'Xbox',
  'Beats',
  'Bose',
  'Yeti',
  'Stanley',
  'Pokemon',
  'Hello Kitty',
  'Coach',
  'Michael Kors',
  'Amazon Basics',
];

export const BLACKLIST_KEYWORDS: string[] = [
  'replica',
  'copy',
  'inspired by',
  'style of',
  'knockoff',
  'oem',
  'authentic',
  'genuine',
  'used',
  'pre-owned',
  'refurbished',
  'renewed',
  'open box',
  'bundle',
  'multipack',
  'multi-pack',
  '2 pack',
  '3 pack',
  '4 pack',
  '5 pack',
  '6 pack',
  'lot of',
  'case of',
];
