// Canonical rejection reason codes.  Stable strings used by every stage
// so downstream analytics can group failures consistently.

export const RejectionReason = {
  // Discovery
  EBAY_API_ERROR: 'EBAY_API_ERROR',
  NO_CANDIDATES_FOUND: 'NO_CANDIDATES_FOUND',
  BAD_SOURCE_DATA: 'BAD_SOURCE_DATA',
  MISSING_TITLE: 'MISSING_TITLE',
  MISSING_CATEGORY: 'MISSING_CATEGORY',

  // ASIN / Amazon
  ASIN_NOT_RESOLVED: 'ASIN_NOT_RESOLVED',
  LOW_CONFIDENCE_ASIN_MATCH: 'LOW_CONFIDENCE_ASIN_MATCH',
  AMAZON_SEARCH_UNAVAILABLE: 'AMAZON_SEARCH_UNAVAILABLE',
  AMAZON_RESOLUTION_NOT_IMPLEMENTED: 'AMAZON_RESOLUTION_NOT_IMPLEMENTED',
  AMAZON_VALIDATION_UNAVAILABLE: 'AMAZON_VALIDATION_UNAVAILABLE',
  AMAZON_PAGE_UNAVAILABLE: 'AMAZON_PAGE_UNAVAILABLE',
  AMAZON_BLOCKED_OR_CAPTCHA: 'AMAZON_BLOCKED_OR_CAPTCHA',
  AMAZON_PRICE_MISSING: 'AMAZON_PRICE_MISSING',
  AMAZON_OUT_OF_STOCK: 'AMAZON_OUT_OF_STOCK',
  AMAZON_NOT_BUYABLE: 'AMAZON_NOT_BUYABLE',
  DELIVERY_TOO_LONG: 'DELIVERY_TOO_LONG',
  DELIVERY_UNCLEAR: 'DELIVERY_UNCLEAR',
  USED_RENEWED_REFURBISHED: 'USED_RENEWED_REFURBISHED',
  AMAZON_BASICS_EXCLUDED: 'AMAZON_BASICS_EXCLUDED',
  BUNDLE_OR_MULTIPACK_EXCLUDED: 'BUNDLE_OR_MULTIPACK_EXCLUDED',
  RESTRICTED_PRODUCT_SIGNAL: 'RESTRICTED_PRODUCT_SIGNAL',
  HAZMAT_SIGNAL: 'HAZMAT_SIGNAL',
  MEDICAL_DEVICE_SIGNAL: 'MEDICAL_DEVICE_SIGNAL',
  WEAPON_SIGNAL: 'WEAPON_SIGNAL',
  FOOD_SUPPLEMENT_SIGNAL: 'FOOD_SUPPLEMENT_SIGNAL',
  SOURCE_VALIDATION_ERROR: 'SOURCE_VALIDATION_ERROR',
  AMAZON_SOURCE_OUT_OF_STOCK: 'AMAZON_SOURCE_OUT_OF_STOCK',
  AMAZON_NO_PRICE: 'AMAZON_NO_PRICE',
  AMAZON_RENEWED_OR_REFURBISHED: 'AMAZON_RENEWED_OR_REFURBISHED',
  AMAZON_BASICS: 'AMAZON_BASICS',
  AMAZON_BUNDLE_OR_MULTIPACK: 'AMAZON_BUNDLE_OR_MULTIPACK',
  AMAZON_DELIVERY_TOO_SLOW: 'AMAZON_DELIVERY_TOO_SLOW',

  // Demand
  DEMAND_CONFIDENCE_TOO_LOW: 'DEMAND_CONFIDENCE_TOO_LOW',
  STAGNATION_TOO_HIGH: 'STAGNATION_TOO_HIGH',

  // Compliance
  COMPLIANCE_HARD_REJECT: 'COMPLIANCE_HARD_REJECT',
  POLICY_RISK_EXCEEDED: 'POLICY_RISK_EXCEEDED',
  RESTRICTED_CATEGORY: 'RESTRICTED_CATEGORY',

  // Final
  FINAL_SCORE_TOO_LOW: 'FINAL_SCORE_TOO_LOW',
  UNSPECIFIED: 'UNSPECIFIED',
} as const;

export type RejectionReasonCode = (typeof RejectionReason)[keyof typeof RejectionReason];
