// Canonical rejection reason codes.  Stable strings used by every stage
// so downstream analytics can group failures consistently.

export const RejectionReason = {
  // Discovery
  EBAY_API_ERROR: 'EBAY_API_ERROR',
  NO_CANDIDATES_FOUND: 'NO_CANDIDATES_FOUND',
  BAD_SOURCE_DATA: 'BAD_SOURCE_DATA',
  MISSING_TITLE: 'MISSING_TITLE',
  MISSING_CATEGORY: 'MISSING_CATEGORY',

  // ASIN / Amazon
  ASIN_NOT_RESOLVED: 'ASIN_NOT_RESOLVED',
  AMAZON_RESOLUTION_NOT_IMPLEMENTED: 'AMAZON_RESOLUTION_NOT_IMPLEMENTED',
  AMAZON_VALIDATION_UNAVAILABLE: 'AMAZON_VALIDATION_UNAVAILABLE',
  AMAZON_SOURCE_OUT_OF_STOCK: 'AMAZON_SOURCE_OUT_OF_STOCK',
  AMAZON_NO_PRICE: 'AMAZON_NO_PRICE',
  AMAZON_RENEWED_OR_REFURBISHED: 'AMAZON_RENEWED_OR_REFURBISHED',
  AMAZON_BASICS: 'AMAZON_BASICS',
  AMAZON_BUNDLE_OR_MULTIPACK: 'AMAZON_BUNDLE_OR_MULTIPACK',
  AMAZON_DELIVERY_TOO_SLOW: 'AMAZON_DELIVERY_TOO_SLOW',

  // Demand
  DEMAND_CONFIDENCE_TOO_LOW: 'DEMAND_CONFIDENCE_TOO_LOW',
  STAGNATION_TOO_HIGH: 'STAGNATION_TOO_HIGH',

  // Compliance
  COMPLIANCE_HARD_REJECT: 'COMPLIANCE_HARD_REJECT',
  POLICY_RISK_EXCEEDED: 'POLICY_RISK_EXCEEDED',
  RESTRICTED_CATEGORY: 'RESTRICTED_CATEGORY',

  // Final
  FINAL_SCORE_TOO_LOW: 'FINAL_SCORE_TOO_LOW',
  UNSPECIFIED: 'UNSPECIFIED',
} as const;

export type RejectionReasonCode = (typeof RejectionReason)[keyof typeof RejectionReason];
